### ISSUE TITLE
Backing up a database takes oodles of disk space 

### ISSUE THREAD

**Issue by damm** [backup/backup#594]
Scenario.

We have a pretty decently sized server with only 400Gb of disk space available.  Our database takes roughly 240Gb which leaves us with 160Gb roughly to work with and backup.  Using the backup gem completely it is impossible to accomplish this.  After reviewing of what takes place I find this humorously sad.  
1. Take a mysqldump
2. Then let's tar it
3. Then let's compress it

Currently a mysqldump without compression takes up 140Gb.  So once you start taring I run out of disk space. 

I can run mysqldump piped directly into gzip and achieve a nice 68Gb.  But then if I use the _archive_ method to ship it up to S3 you are only going to _tar_ it and then _compress_ it again.  

This is really bad

Lastly I have noticed #255 I think being able to disable tar'ing would be a great start.

**Comment by epcim** [comment]
+1 

instead of /bin/cat > '/Users/tom/Backup/.tmp you may use FIFO pipes or do some "socket streaming" to the uploader. The issue here is that "mysql dump" on 140GB will write to "cache" faster then the uploader will take, so we will end up anyway.

btw:
backup 100GB of mysql this way is insane, unless you run parallel streams out of the instance,
better to use XFS + filesystem snapshots, yes then you wont be able to do table recovery IMHO

**Comment by damm** [comment]
Unfortunately I couldn't really resolve this with the backup gem; I ended up writing my own backup routines using [Fabric](http://www.fabfile.org/).  

I ended up needing to throttle the upload to not abuse our 95th percentile; don't see how this can be done natively with the backup gem.  

The amount of disk thrash using the backup gem is quite absurd doing a mysqldump.

This is how it appears to me; I maybe wrong.  
```shell
mysqldump > outfile
cat outfile > /tmp/.tmp/outfile
tar cf outfile.tar /tmp/.tmp/*
gzip outfile.tar
```

I don't really promote the backup gem as much as I used to; a lot of people ask about what about restoring? Well the backup gem only backs up.
