### ISSUE TITLE
backup perform --trigger is loading other modules

### ISSUE THREAD

**Issue by fabrouy** [backup/backup#652]
Hey guys, I hope this is not a silly question.

I have multiple models inside models folder like so:
~/Backup/models/red.rb
~/Backup/models/green.rb

red.rb:

```ruby
raise "Why am I here?"
Model.new(:red, 'Backup for red') do
    # ...
end
```

green.rb:

```ruby
Model.new(:green, 'Backup for green') do
    # ...
end
```

When I do: `backup perform --trigger green` I get:

```bash
[2015/04/08 21:15:34][error] CLI::Error
[2015/04/08 21:15:34][error] --- Wrapped Exception ---
[2015/04/08 21:15:34][error] RuntimeError: Why am I here?
```

If I delete `red.rb`, green backup is successfull.

Any ideas? Thank you very much!

**Comment by tombruijn** [comment]
@fabrouy it's correct that all the models are loaded (required) on start up. It should however, not execute the actual backup procedure. So that the file is loaded should not be a problem.

There is already a feature request accepted for version 5 to only load the config for a specific trigger. https://github.com/backup/backup-features/issues/10

**Comment by fabrouy** [comment]
Thanks @tombruijn for your time. Sorry, I didn't know there was a better place for this discussion.

I am glad this feature will be added in a future release. In my case I have staging and production apps set up in the same box and will be nice being able to backup them both separately (loading idependent yaml files in each model)

Cheers!
