### ISSUE TITLE
AWS:SES IAM Option

### ISSUE THREAD

**Issue by darrylb-github** [backup/backup#666]
Hi,

Is it possible at the moment to use an IAM profile to authenticate the AWS:SES notifier? I'm using IAM for the s3 storage (`s3.use_iam_profile = true`) and would like to use this for SES notifications as well without having to specify the access key and secret in the backup model. Something like `ses.use_iam_profile = true`.

Thanks,
D

**Comment by tombruijn** [comment]
Currently it doesn't look like it's supported in the SES notifier. I looked at how the S3 integration supports it and it looks like it's handled through fog. Since the SES notifier doesn't use fog to send notifications but [aws-ses](https://rubygems.org/gems/aws-ses) instead. I can't find any specific mentions of using IAM profiles to authenticate so I can't tell if it's supported or not.
