### ISSUE TITLE
config.rb/tmp_path appears to be not respected

### ISSUE THREAD

**Issue by TemporarilyOffline** [backup/backup#668]
I have tried 

`tmp_path  '/mnt/backup'`
`tmp_path = '/mnt/backup'`
`tmp_path('/mnt/backup')`

and setting `--tmp_path /mnt/backup` on the cli.  

Setting on the CLI worked fine, the config.rb examples do not.  When there are no CLI options, the tmp_path is actually root_path/.tmp.  root path is specified on the command line so that it knows where to find config.rb.

**Comment by tombruijn** [comment]
`tmp_path = '/mnt/backup'` will not work because you're assigning a local variable there. The other two should work.

So you're already using `--root-path` in this scenario? But then it doesn't 
Can you post your complete config please?

**Comment by TemporarilyOffline** [comment]
My command line:

    /usr/bin/backup perform --trigger rotation --root-path /var/backup

My config file:

    # encoding: utf-8

    ##
    # Backup v4.x Configuration
    #
    # Documentation: http://meskyanichi.github.io/backup
    # Issue Tracker: https://github.com/meskyanichi/backup/issues

    root_path '/var/backup'
    tmp_path  '/mnt/backup'
    data_path '/var/backup/data'

    Logger.configure do    
      console.quiet     = true            # Same as command line: --quiet
      logfile.max_bytes = 2_000_000       # Default: 500_000
      syslog.enabled    = false           # Same as command line: --syslog     
      syslog.ident      = 'BACKUP' # Default: 'backup'             
    end    

    Storage::S3.defaults do |s3|  
      s3.access_key_id        = "access_key_id"
      s3.secret_access_key    = "secret_access_key"  
      s3.bucket               = "bucket-name"
      s3.region               = "region"
      s3.path                 = "path"
    end

**Comment by tombruijn** [comment]
@TemporarilyOffline woops.. I can confirm that this doesn't work.. Sorry about that.

The problem seems to be here:
https://github.com/backup/backup/blob/289489727698e7f6bd4648b823da6b17a7c556f8/lib/backup/config.rb#L44-L45

Line 44: The values from your config file are set.
Line 45: Paths are overridden if they are given through the CLI.

However, the contents of that hash are:

```ruby
{"config_file"=>"",
 "root_path"=>"/Users/tom/Desktop/backup",
 "data_path"=>"",
 "log_path"=>"",
 "tmp_path"=>"",
 "quiet"=>false,
 "syslog"=>false,
 "logfile"=>true,
 "check"=>false,
 "trigger"=>"issue_668"}
```

All the path values are empty. When they are being updated this empty value is set and then the next time backup asks for those paths it finds no value and falls back on the default.

I'll start looking for a fix. In the meantime you have to supply these paths through the CLI apparently it's the only config it really listens to.

**Comment by TemporarilyOffline** [comment]
Thanks Tom!

**Comment by tombruijn** [comment]
@TemporarilyOffline some bad news. I spend some 4 hours on this problem (yes, I use a time tracker) and it's difficult to fix. Well not this problem, but everything else around it. The config paths have so many damn conditionals on the whole configuration section that adding another exception to it is almost impossible. I now have it down to 21 failing specs, but I'm giving up.

I can much better spend my time on the next version where we already sorted the configuration out.

I hope the workaround of setting everything on the CLI works for now.
