### ISSUE TITLE
Backup Truck Factor

### ISSUE THREAD

**Issue by gavelino** [backup/backup#687]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Backup** and obtained a value of **2**.

The developers responsible for this TF are:

Brian D. Burns - author of 85% of the files
Michael van Rooijen - author of 31% of the files

To validate our results, we would like to ask **Backup** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Backup**?

(b) Do you agree that **Backup** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Backup** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by tombruijn** [comment]
I see you posted __a lot__ of these kinds of issues on repositories, seems really spammy and off-topic. This is an issue tracker, not a place for a general discussion. An email or [Gitter](Gitter.im/backup/backup) would have been better.

But anyway, since this is here now:

> (a) Do you agree that the listed developers are the main developers of Backup?

No, Burns hasn't been contributing for a while now. I've taken over what he was doing.

> (b) Do you agree that Backup will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

Backup shouldn't be in trouble just because the current developers get hit by trucks. It's an open source project, anyone can start contributing if they want to. It might not continue in it's current form, but people will find a way to keep using it.

I actually got hit by car recently and I didn't respond to issues for a while. I hope we will find someone else to help out if it had been more serious.

Me winning the lottery would actually help the project, because I wouldn't have to worry about money anymore and let me work on what I want.

> (c) Does Backup have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Backup has good documentation to solve most configuration problems. The code itself is readable and documented, and we have plenty of specs to detect problems.

**Comment by gavelino** [comment]
Thank you.
