### ISSUE TITLE
Feature request: Custom notifier message/stats 

### ISSUE THREAD

**Issue by itatabitovski** [backup/backup#710]
I would find it useful if backup can return some stats after the backup such as:
- file size (for storages where it is possible)
- size of the archive folder/bucket
- checksum of the file
- duration of backup run

Depending of the notifier they can be pushed in different ways, either as a text or as separate metrics that a user can select to receive.

**Comment by tombruijn** [comment]
You can already customize the notifier messages to include some of this since v4.2.0, see also #698.

The things you're asking for:

- File size
  - Currently not recorded. Planned for the next major release
- Size of the archive folder
  - Currently not supported. Not sure if we would want to ask the remote storage for this or should just return a sum of all registered backups.
- Checksum
  - Currently not supported
  - See also https://github.com/backup/backup-features/issues/29
- Duration
  - see [Model.duration](http://www.rubydoc.info/gems/backup/Backup/Model#duration-instance_method)

**Comment by itatabitovski** [comment]
Thanks!

I will take a look at the things you pointed out. Feel free to close this issue.
