### ISSUE TITLE
encoding: utf8mb4 for protecting emoji chars

### ISSUE THREAD

**Issue by rezam90** [backup/backup#728]
Hi
MySQL uses encoding: utf8mb4 for saving emoji chars. but when I try to restore the backed up file, all emoji chars are converted to ????
I think the db is backed up with utf-8 encoding.
any Idea? How can I fix this?
Is there any option for this? like below?
```ruby
database MySQL do |db|
    # To dump all databases, set `db.name = :all` (or leave blank)
    db.name        = "db_production"
    db.username    = "root"
    db.password    = "password"
    db.host        = "localhost"
    db.encoding    = "utf8mb4"    # this one !
end
```

**Comment by tombruijn** [comment]
Backup doesn't set any specific settings for backing up specific databases such as encodings. I would expect the mysql backup tools to honor the settings in the tables (because that would kind of make sense). In case it doesn't you can set additional `mysqldump` settings (the utility backup uses) through `additional_options = ["--option=value"]`

maybe `db.additional_options = ["--default-character-set=utf8mb4"]` would work?

**Comment by rezam90** [comment]
:+1: 
Thanks, this fixed the problem.
```ruby
db.additional_options = ["--default-character-set=utf8mb4"]
```
