### ISSUE TITLE
syslog not available on Windows

### ISSUE THREAD

**Issue by rraub** [backup/backup#772]
I'm getting a failure to load syslog from https://github.com/backup/backup/blob/c63ac95ba778fc3d825a516d70070a0c154d55a4/lib/backup.rb#L7 on a fresh Windows Server 2008 box running ruby 2.2.4 and backup 4.2.3.

From my research it looks like syslog isn't a core class on windows isn't available for obvious reasons. There are replacements, but the current backup implementation doesn't provide any support for them.

**Comment by tombruijn** [comment]
Hi @rraub, I'm not sure what to do here. I'm not even aware of any support for windows. It would of course be nice if it would work, but because backup has so many dependencies we can't be sure they will work on windows either.

If we would want to support windows, what is a recommended system to use for logging?

**Comment by rraub** [comment]
I'm not a big windows person, but the simple common answer to lots of ruby apps in windows is running them in cygwin. Windows support is hard for packages like this, at least this gem could note that in the docs.

**Comment by tombruijn** [comment]
I'm going to close this issue. Windows is not supported.
