### ISSUE TITLE
installing backup via Gemfile not finding version > 3.4.0

### ISSUE THREAD

**Issue by aussiDavid** [backup/backup#773]
When I include the backup gem in my Gemfile then check the version, it shows that it has installed version 3.4.0.

When I go to install the gem manually it installs version 4.2.3.

Is there something I am missing?

Regards,

**Comment by tombruijn** [comment]
Hi @aussiDavid, when you're manually installing it do you mean you `gem install backup`? 

If you want to install another version than the latest version use the version flag `gem install backup --version "3.4.0"`

However, I recommend using bundler for selecting versions and running it through bundler.

**Comment by aussiDavid** [comment]
yes, when I installed it manually I did 
`$ gem install backup
`
The issue is when I add the backup gem to my Gemfile
`gem 'backup'
`
I'm only getting version 3.4.0.

**Comment by tombruijn** [comment]
That's because you have version 3.4.0 on your machine and bundled uses that first. Run "bundle updat backup" to update it. 

If that doesn't work there's probably another gem in your gemfile that conflicts with backup's dependencies, not allowing it to install a version higher than 3.4.0. If this is the case you probably have it in another projects gemfile which is not recommend. Please create a new projects with its own gemfile where you install and configure backup. 

See also this page for more information: http://backup.github.io/backup/v4/installation/
