### ISSUE TITLE
Unable to activate backup due to conflicts with thor gem

### ISSUE THREAD

**Issue by gowthamgts** [backup/backup#836]
Hello, I tried to run backup in a recently provisioned VPS and got the following error when I ran `backup`:
```
/home/gts/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate backup-4.4.0, because thor-0.19.4 conflicts with thor (= 0.18.1) (Gem::ConflictError)
```

Actually, I tried to install this gem in a server where a rails application is deployed via Capistrano.

* Operating system: Ubuntu Server 16.04.1
* Ruby version: 2.3.3

**Comment by stuartellis** [comment]
Hello Gowtham,

I think that you might have already spotted the problem: both Backup and Rails depend on Thor, so  you need to have separate sets of gems for Rails and Backup.

There are various ways to do this, so you can choose the one that is easiest for you. For example, you could use [rbenv-gemset](https://github.com/jf/rbenv-gemset), or you could create a separate user account on the server for Backup.

**Comment by gowthamgts** [comment]
Thanks @stuartellis for your reply. I'll try `rbenv-gemset` and will update this thread.

**Comment by feliperaul** [comment]
@stuartellis Thanks for your effort on this awesome gem and support. The problem is:
- First I intended to use the different user route; it seemed easier, and I followed Digital Ocean's tutorial to create a new user, add it to sudo group, disable password access and add my keys. Only then I found out that my RVM installation was done in single user mode, so I would have to duplicate RVM/Ruby installation in this user as well. I gave up, it's a small VPS for a personal project and I can't afford the duplication.
- Then I decided to take a look at the rbenv-gemset gem, but since I used RVM to install Ruby I thought this was going to lead to conflict.

Don't get me wrong, but I think the majority of the users of this gem are not (and wish not) to be system admins. We just want to have a nice and simple way of setting up a backup for our servers, and that's why we'd like to use the gem. This conflict issue caused me 1.5 hours of headaches and I still can't even initialize the gem. 

Isn't there any other simpler way of solving this

**Comment by gowthamgts** [comment]
@feliperaul Hey, I solved this by building the gem locally and using it. For more information on this check [this commit](https://github.com/gowthamgts/backup/commit/79d888b66f7e377b01cf6bedc6c148609bd57d87).

**Comment by stuartellis** [comment]
@feliperaul I do sympathize: I am a system admin, and I sometimes find it annoying!

Unfortunately, these kinds of issues come with using Ruby: IMO, you really need to run each Ruby application in a separate environment. There are also lots of ways to do this, so we can't just tell everyone to follow one set of instructions.
