### ISSUE TITLE
Dropbox APIv2

### ISSUE THREAD

**Issue by mdarii** [backup/backup#838]
Hi,

Dropbox will disable APIv1 on 28th June, also they don't provide anymore official SDK for ruby:
https://github.com/dropbox/dropbox-sdk-ruby/issues/41
https://www.dropbox.com/developers/documentation/communitysdks
and suggest to use direct api calls or community one:
https://github.com/waits/dropbox-sdk-ruby
What are yours plans about dropbox support in future?

**Comment by stuartellis** [comment]
Hello @mdarii,

Thank you for letting us know. If you or someone else is interested in working on this, please do!

I can't say that there is a specific plan - there are so many providers that we do need people that have an interest in particular services either letting us know if they need fixes, or contributing code.

**Comment by shakycode** [comment]
@stuartellis I'm also in this sameboat using Dropbox as a dump for our backups from the backup gem.  I'd be happy to fork backup and try to come up with a solution for the API V1 deprecation.  Do you have a contributors guide so I know what I'm jumping into?  This is a problem that I think many of us would like to see solved.  I'd be happy to take a stab at it.

**Comment by stuartellis** [comment]
Hello @shakycode, there's currently this:

https://github.com/backup/backup/blob/master/CONTRIBUTING.md

Other points: we currently have an open ticket for Ruby 2.4, so please use 2.3 for now, and also we use Rubocop for consistent code style (you will see that there's Rake tasks).

Please do ping us on Gitter if you have questions or need help.

**Comment by shakycode** [comment]
@stuartellis Thanks so much, I'll fork and start working on this.  I'll keep locked at ruby 2.3.  2.4 is still not totally stable from what I've seen.

**Comment by nynhex** [comment]
I'm still looking into dropbox v2 API integration for the next release, but it's slow going as I'm super busy with work and my startup.  So far the API is not all the "pleasant" to work with without the Ruby SDK..  This won't be supported anytime soon unless someone else picks this up.

Personally I've switched my storage method to s3 and am happier with it than with Dropbox.  s3 by default is more secure (or can be).  So I would recommend to all users that they switch their storage method to s3 since it's well supported.

It should be noted that the aws-sdk gem that is a dependency now requests a hostname in addition to bucket name, region, and keys.  I ran into this on another project.

**Comment by hiphapis** [comment]
@nynhex you known, @vtm9 are sent PR https://github.com/backup/backup/pull/901

**Comment by nynhex** [comment]
@hiphapis Yes, have seen that.  Reviewing this week, if it's solid and @tombruijn @stuartellis agree, I will merge and we can cut a new release.

**Comment by vtm9** [comment]
@nynhex,  PR in wip state,  because I have problems with integration test and maintainer of gem Dropbox api v2,  do not merge my PR with chucked uploader.  I can move uploader class to backup gem, but image with Vagrant does not exists,  and I can't start integration tests. May be anybody have it?

**Comment by stuartellis** [comment]
Testing is my main concern. @vtm9 is right - the integration test suite in the vagrant/ directory doesn't work, because the image is MIA. I've restarted development of #857, so that we can use Docker for integration tests. We could also create a new image for Vagrant.

Either way, I feel that we should have a reasonable test process for Dropbox before we advertise that we support it again.

**Comment by vtm9** [comment]
@stuartellis, may be we merge your tests with Docker to master, and after that I'll add Dropbox supporting with good test coverage?
