### ISSUE TITLE
Redis fail: Errno::EPERM: Operation not permitted - 'redis-cli' returned exit code: 1

### ISSUE THREAD

**Issue by fredsted** [backup/backup#866]
## What went wrong?

We recently had a backup fail due to the message in the title. It only failed once with that message. I'm wondering what it means. 

Does backupv4 not have permission to execute the `redis-cli` binary? 

Was it not able to access to the  Redis server?

## How is your copy of backup configured?

config:
```
# encoding: utf-8

##
# Backup v4.x Configuration
#
# Documentation: http://backup.github.io/backup
# Issue Tracker: https://github.com/backup/backup/issues

##
# Logging
#
# Logging options may be set on the command line, but certain settings
# may only be configured here.
#

Logger.configure do
  console.quiet     = true            # Same as command line: --quiet
  logfile.max_bytes = 2_000_000       # Default: 500_000
  syslog.enabled    = true            # Same as command line: --syslog
  syslog.ident      = 'backup' # Default: 'backup'
```

model:
```
  # Redis
  database Redis do |db|
    db.mode               = :sync
    db.invoke_save        = false
    db.host               = 'redis.prod.local'
    db.port               = 6379
    db.password           = ''
    db.additional_options = []
  end
```

## Tell us about the computer that runs the backup gem

* Operating system: Ubuntu Server 16.04
* Ruby version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
* Tools or services used by backup: Redis 3.2.5

**Comment by stuartellis** [comment]
@fredsted - I can't be sure without seeing the exact error in context, but since it failed once and then worked, it is most likely to be a network or server error. By default, Backup uses the privileges of whatever user runs it.

I'm going to close the issue, since it only happened once for you. If this does happen again, please try running the Redis CLI from the same computer to see whether you have a general issue connecting to Redis. Obviously, if the problem only occurs when you use Backup, please feel free to re-open this issue.
